version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  aws-cli: circleci/aws-cli@3.1.5

jobs:
  build-and-push:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Authenticate Docker with ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION |
            docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - run:
          name: Build Docker image
          command: docker build -t $ECR_REPOSITORY_NAME .
      - run:
          name: Tag and Push Docker image
          command: |
            docker tag $ECR_REPOSITORY_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$CIRCLE_BUILD_NUM
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$CIRCLE_BUILD_NUM

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-push:
          context: AWS
