version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  aws-cli: circleci/aws-cli@3.1.5
  node: circleci/node@5.1.0

jobs:
  build-and-push:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # Configure AWS credentials
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      
      # Build and push Docker image
      - aws-ecr/build-and-push-image:
          repo: ${ECR_REPOSITORY_NAME}
          tag: "${CIRCLE_SHA1},latest"
          dockerfile: Dockerfile
          path: .
          registry-id: AWS_ACCOUNT_ID

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-push:
          context: AWS